export const produtosEstoque = [
  {
    codigo: "PRD-0021",
    nome: "Farinha de Trigo",
    categoria: "Alimentos",
    fornecedor: "Alimentos Silva Ltda",
    preco: "R$ 8,90",
  },
  {
    codigo: "PRD-0089",
    nome: "Sabão em Pó",
    categoria: "Limpeza",
    fornecedor: "Clean Maxx",
    preco: "R$ 12,50",
  },
  {
    codigo: "PRD-0150",
    nome: "Arroz Branco 5kg",
    categoria: "Alimentos",
    fornecedor: "Cerealista Brasil",
    preco: "R$ 25,00",
  },
  {
    codigo: "PRD-0210",
    nome: "Detergente Líquido",
    categoria: "Limpeza",
    fornecedor: "Higiclean",
    preco: "R$ 3,50",
  },
  {
    codigo: "PRD-0305",
    nome: "Café Torrado 500g",
    categoria: "Alimentos",
    fornecedor: "Café do Sul",
    preco: "R$ 14,90",
  },
  {
    codigo: "PRD-0412",
    nome: "Shampoo Anticaspa",
    categoria: "Higiene",
    fornecedor: "Beleza Natural",
    preco: "R$ 19,90",
  },
  {
    codigo: "PRD-0520",
    nome: "Papel Higiênico 12 rolos",
    categoria: "Higiene",
    fornecedor: "SoftPaper",
    preco: "R$ 22,00",
  },
  {
    codigo: "PRD-0633",
    nome: "Óleo de Soja 900ml",
    categoria: "Alimentos",
    fornecedor: "AgroBrasil",
    preco: "R$ 7,50",
  },
  {
    codigo: "PRD-0744",
    nome: "Desinfetante Floral",
    categoria: "Limpeza",
    fornecedor: "Limpex",
    preco: "R$ 6,90",
  },
];